accounts/media/__init__.py
from .admin import MediaView
from .base import Media
from .gridfs import GFSMedia
from .blueprint import media_blueprint
from ..admin import Admin
from . import graphql
from . import crypto
from .s3 import (
  S3Object, 
  cloudfront_signer
)

def install_media(flask_app, private_key=None):

  if private_key:
    crypto.policy_parser = crypto.PolicyEncoder(
      private_key = private_key
    )

  Admin.add_view(
    MediaView(
      Media,
      name="Media",
      category="Media"
    )
  )
  Admin.add_view(
    MediaView(
      S3Object,
      name="Amazon S3",
      category="Media"
    )
  )
  Admin.add_view(
    MediaView(
      GFSMedia,
      name="Grid Fs",
      category="Media"
    )
  )

  if csrf := flask_app.extensions.get('csrf'):
    flask_app.register_blueprint(
      csrf.exempt(media_blueprint)
    )
  else:
    flask_app.register_blueprint(media_blueprint)

__all__ = [
  "Media"
  "Media",
  "GFSMedia",
  "S3Object", 
  "cloudfront_signer", 
  "s3_signer"
]

accounts/media/blueprint.py
from flask_wtf.csrf import validate_csrf
from . import crypto
from ..sessions import current_user
from .base import Media
from json import dumps
from .utils import (
  get_file_size,
  get_media_model,
  validate_file_properties
)
from flask import (
  Blueprint, 
  request, 
  Response,
  url_for,
  redirect,
  flash,
  session
)

media_blueprint = Blueprint('storage', __name__, url_prefix="/media")

@media_blueprint.route('/objects/', methods=["POST"])
def upload():
  
  try:

    file = request.files.get('file')
    form = request.form
    assert file is not None, "File is not present"
    model = get_media_model(form.get('model'))
    assert model is not None, f"{form.get('model')} is not a registered model"
    content_length_range = model.content_length_range or [1, 16_000_000]
    content_length=int(request.headers.get('Content-Length') or 0)
    assert content_length <= 16_000_000, "File too large (16mb max)"
    validate_file_properties(
      content_type=file.content_type,
      content_types=getattr(model, 'content_types', []),
      content_length_range=content_length_range,
      content_length=content_length
    )
    if 'policy'in form and 'signature' in form:

      crypto.policy_encoder.decode(
        "put_object",
        form['policy'],
        form['signature']
      )
      instance = model.upload_file(file)
      return Response(
        dumps(instance.to_mongo(), default=str),
        status=200,
        mimetype="application/json"
      )

    if 'csrf_token' in form:

      validate_csrf(form['csrf_token'])
      file = request.files.get('file')
      model = get_media_model(form.get('model'))
      instance = model.upload_file(file)
      flash(f'{instance.file_name} has been uploaded')
      return redirect(url_for(request.args.get('next')))

  except Exception as e:
    if request.args.get('next'):
      flash(str(e))
      return redirect(url_for(request.args.get('next')))
    return Response(str(e), status=401)

  return Response("Invalid request", status=401)


@media_blueprint.route('/objects/<id>/', methods=["GET"])
def get_object(id):

  media = Media.objects.filter(
      id=id
    ).first()

  try:

    assert media is not None, \
      "Requested object does not exist"

    if media.access == "public":
      return media.serve_file()


    elif media.access == "authenticated_read":
      assert current_user != None, \
        "Log in required"
      return media.serve_file()

    elif media.access == "private":

      assert all([
        'policy' in request.args,
        'signature' in request.args,
        current_user != None
      ]), "Access Denied"

      policy = crypto.policy_encoder.decode(
        'get_object',
        request.args['policy'],
        request.args['signature']
      )

      assert policy['resource'] == id, \
        "Policy resource does not match object id"

      return media.serve_file()
    
    else:
      raise Exception('file access type not supported')

  except Exception as e:
    return Response(str(e), status=500)

accounts/media/templates/upload_form.html
{% extends 'admin/model/create.html' %}

{% block create_form %}
<form 
  class="m-4" 
  action="{{url_for('storage.upload', next=request.endpoint)}}" 
  method="POST" 
  enctype="multipart/form-data">
  <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
  <div class="mb-3">
    <label for="exampleFormControlInput1" class="form-label">Select File</label>
    <input class="form-control" type="file" id="file" name="file">
    <input name="model" type="hidden" value="{{admin_view.model.__name__}}">
  </div>
  <div class="mb-3">
    <input type="submit" value="Upload" />
  </div>
</form>
{% endblock %}

accounts/media/templates/upload_view.html
{% extends 'admin/model/create.html' %}

{% block create_form %}
<script src="https://cdn.jsdelivr.net/npm/vue@2.7.13"></script>
<div id="app"
    class="file-uploader"
    :class="{'drag-highlight': draggingFiles}" 
    @dragover="handleDragOver" 
    @drop="handleFileDrop" 
    @dragleave="handleDragEnd">
      <button 
      class="selector-button" 
      @click="$refs.fileSelector.click()">
      Select Files or Drag and Drop
      </button>
      <input 
      style="display: none;"
      ref="fileSelector"
      type="file"
      @change="handleFilesSelected" 
      multiple="multiple"
      />
      <table width="100%" v-if="files.length > 0">
        <tr class="table-heading">
          <th>
            File Name
          </th>
          <th>
            Status
          </th>
          <th>
            Size
          </th>
          <th>
            Progress
          </th>
        </tr>
        <tr 
        v-for="file, index in files" 
        :key="index" 
        class="file-uploader-item">
          <td>
            {{"{{file.fileName}}"}}
          </td>
          <td style="text-transform: capitalize;">
            {{"{{file.status}}"}}
          </td>
          <td style="text-transform: capitalize;">
            {{"{{file.size / 1000000}} mb"}}
          </td>
          <td v-if="file.status == 'failed'">
            <button @click="handleRetry(file)">Retry</button>
          </td>
          <td v-else>
            {{"{{file.progress}}"}}%
          </td>
        </tr>
      </table>
      </div>
    </div>
    <script>

      class FileContainer {
        constructor(file) {
          this.file = file
          this.status = "pending"
          this.selected = false
          this.request = null
          this.progress = 0
        }
        get fileName() {
          return this.file.name
        }
        get contentType() {
          return this.file.type
        }
        get size() {
          return this.file.size
        }
        makeForm(fields) {
            const formData = new FormData();
            for (const[key, val] of Object.entries(fields))
              formData.append(key, val);
          formData.append('file', this.file)
          return formData
        }
        upload(presignedPost, progressCallback) {
          this.status = 'uploading'
          const {fields, url} = presignedPost
          const form = this.makeForm(fields)
          return new Promise((res, rej) => {
            const http = new XMLHttpRequest()
            this.request = http
            http.withCredentials = true;
            http.upload.onprogress = (e) => {
              if (e.lengthComputable) {
                const done = e.position || e.loaded,
                total = e.totalSize || e.total;
                const progress = Math.round((done / total * 1000) / 10);
                this.progress = progress
                if (progressCallback) 
                  progressCallback(progress)
              }
            }
            http.open("POST", url)
            http.onload = () => {
              this.status = "completed"
              res(http.response)
            }
            http.onerror = (e) => {
              console.log(http)
              this.status = "failed"
              rej(e)
            }
            http.send(form)
          })
        }
      }

      function GQLRequest(endpoint, query, variables) {
        return new Promise((res, rej) => {
          const http = new XMLHttpRequest();
          this.currentRequest = http
          http.open("POST", endpoint);
          http.withCredentials = true;
          http.setRequestHeader(
            "Content-Type", 
            "application/json;charset=UTF-8"
          );
          const data = {
            query,
            variables
          }
          http.onload = () => res(JSON.parse(http.response))
          http.onerror = (err) => rej(err)
          http.send(JSON.stringify(data))
        });
      }

      const presignedPostQuery = `
      mutation ($media: MediaPostInputType!) {
        generatePresignedPost(media: $media) {
          link
        }
      }`
          
      const mediaUploader = {
        el: "#app",
        data() {
          return {
            endpoint: "/graphql/",
            files: [],
            uploading: false,
            draggingFiles: false
          }
        },
        watch: {
          uploading(v) {
            if (v)
              window.onbeforeunload = function() {
                return "A file is still being uploaded, do you want to cancel?";
              }
            else
              window.onbeforeunload = null
          },
          files() {
            this.startUpload()
          }
        },
        methods: {
          handleRetry(fileEntry) {
            fileEntry.status = 'pending'
            this.startUpload()
          },
          handleDragOver(event) {
            this.draggingFiles = true
            event.preventDefault()
          },
          handleDragEnd() {
            this.draggingFiles = false
          },
          handleFileDrop(event) {
            event.preventDefault();
            if (event.dataTransfer.items) {
              [...event.dataTransfer.items].forEach((item, i) => {
                if (item.kind === 'file') {
                  const file = item.getAsFile();
                  this.addFile(file)
                }
              });
            }
          },
          handleFilesSelected(event) {
            [...event.target.files].forEach(file => {
              this.addFile(file)
            })
          },
          removeFile(fileItem) {
            this.files = this.files.filter(
              fi => fi !== fileItem
              )
          },  
          addFile(file) {
            const entry = new FileContainer(file)
            entry.onprogress = (o) => {
              console.log("onp", o)
              this.$nextTick
            }
            this.files = [...this.files, new FileContainer(file)]
          },
          getNextFile() {
            return this.files.find(
              f => f.status == 'pending'
            )
          },
          getPresignedPost(fileEntry) {
            return GQLRequest(
              this.endpoint,
              presignedPostQuery,
              {
                media: {
                  file:{
                    "fileName": fileEntry.fileName, 
                    "contentType": fileEntry.contentType,
                    "access": "private",
                    "contentLength": fileEntry.size
                  },
                  "resource":"{{admin_view.model.__name__}}"
                }
              }
            )
          },
          async startUpload() {
            if (this.uploading) return
            let nextFile = this.getNextFile();
            if (nextFile) {
              try {
                this.uploading = true
                const postResponse = await this.getPresignedPost(nextFile)
                const presignedPost = postResponse.data.generatePresignedPost.link
                await nextFile.upload(presignedPost)
                this.uploading = false
              } catch(e) {
                nextFile.status = "failed"
                this.uploading = false
                this.startUpload()
                console.log(e)
              }
              this.uploading = false
              this.startUpload()
            }
          }
        }
      };
      new Vue(mediaUploader)
    </script>

    <style>
      .table-heading {
        border:#4fc08d solid 1px;
      }
      .file-uploader {
        border: 1px rgb(216, 216, 216) solid;
        border-radius: 3;
        padding: 15px;
      }
      .drag-highlight {
        border: 1px solid turquoise;
      }
      #app {
        font-family: Avenir, Helvetica, Arial, sans-serif;
        text-align: center;
        color: #2c3e50;
        margin-top: 60px;
      }

      a,
      button {
        color: #4fc08d;
      }

      button {
        background: none;
        border: solid 1px;
        border-radius: 2em;
        font: inherit;
        padding: 0.75em 2em;
      }
    </style>
{% endblock %}